services:
  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./core-service:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://core-mongodb:27017
      - MONGODB_DB_NAME=core_db
      - MONGODB_COLLECTION=vehicles
    depends_on:
      - core-mongodb

  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sales-service:/app
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://sales-mongodb:27017
      - MONGODB_DB_NAME=sales_db
      - MONGODB_COLLECTION=sales
      - CORE_SERVICE_URL=http://core-service:8000
    depends_on:
      - sales-mongodb
      - core-service

  core-mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - core-mongodb-data:/data/db

  sales-mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - sales-mongodb-data:/data/db

volumes:
  core-mongodb-data:
  sales-mongodb-data:
