services:
  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./core-service:/app
    environment:
      - MONGODB_URL=mongodb://core-mongodb:27017
      - MONGODB_DB_NAME=core_db
      - MONGODB_COLLECTION=vehicles
    depends_on:
      - core-mongodb

  core-mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - core_mongodb_data:/data/db

  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./sales-service:/app
    environment:
      - MONGODB_URL=mongodb://sales-mongodb:27017
      - MONGODB_DB_NAME=sales_db
      - MONGODB_COLLECTION=sales
      - PYTHONPATH=/app
    depends_on:
      - sales-mongodb
      - core-service

  sales-mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - sales_mongodb_data:/data/db

volumes:
  core_mongodb_data:
  sales_mongodb_data:
