FROM python:3.11-slim

WORKDIR /app

# Instala dependências de desenvolvimento
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia os arquivos de requisitos e setup
COPY requirements.txt .
COPY setup.py .

# Instala o pacote em modo de desenvolvimento
RUN pip install -e .[dev]

# Copia o código fonte
COPY . .

# Se estiver rodando testes, use o .env.test
ARG ENV_FILE=.env.test
COPY ${ENV_FILE} .env

# Configura o PYTHONPATH
ENV PYTHONPATH=/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"] 